--SCALAR DATA TYPES


----COMPOSITE 
	--RECORD
	--DIFF.DATATYPES CAN BE STORED
			--TYPE,%ROWTYPE
DECLARE
TYPE ADD_REC_TYPE IS RECORD (NAME VARCHAR(3),...PIN NUMBER);
LV_ADD_TYPE ADD_REC_TYPE;
BEGIN
LV_ADD_TYPE.NAME:=;
END;
/

DECLARE
TYPE EMP_REC_TYPE IS RECORD (ENAME EMP.ENAME%TYPE,
							 SAL EMP.SAL%TYPE);
LV_EMP_REC_TYPE 	EMP_REC_TYPE;
					
BEGIN
SELECT ENAME,SAL INTO LV_EMP_REC_TYPE
FROM EMP WHERE ENAME='';
END;
/

	--COLLECTION
--ONLY SAME DATA TYPE CAN BE STORED	
		--VARRAY, NESTED TABLE, ASSOC.ARRAY
		
----VARRAY
DECLARE
TYPE V_ARRAY_TYPE IS VARRAY(7) OF VARCHAR2(30);



---------------

CREATE OR REPLACE TYPE EMP_ROW AS
OBJECT (EMPID NUMBER,ENAME VARCHAR(100),SAL NUMBER)
/

CREATE OR REPLACE TYPE T_EMP_LIST IS TABLE OF  EMP_ROW;
/
CREATE OR REPLACE FUNCTION EMP_REF
RETURN T_EMP_LIST 
AS 
LV_EMP_LIST_1 T_EMP_LIST:=T_EMP_LIST();


TYPE T_ENAME IS TABLE OF VARCHAR2(100);
LV_T_ENAME1 T_ENAME;
TYPE EMP_LIST IS RECORD (ID NUMBER,NAME VARCHAR(30));
LV_EMP_LIST EMP_LIST;
BEGIN

FOR I IN (SELECT EMP_ID,EMP_NAME,SALARY FROM EMP)
LOOP
LV_EMP_LIST_1.EXTEND;
LV_EMP_LIST_1(LV_EMP_LIST_1.LAST):=EMP_ROW(I.EMP_ID, I.EMP_NAME, I.SALARY);
END LOOP;
RETURN LV_EMP_LIST_1;
--SELECT EMP_ID,EMP_NAME
--BULK COLLECT INTO LV_EMP_LIST
--FROM EMP;


END;
/

CREATE OR REPLACE FUNCTION EMP_REF_1
RETURN SYS_REFCURSOR 
AS 
LV_REF_CURSOR SYS_REFCURSOR;
BEGIN

OPEN LV_REF_CURSOR
FOR SELECT * FROM EMP;

RETURN LV_REF_CURSOR;

END;
/
SET SERVEROUTPUT ON
/
DECLARE
LV_REF SYS_REFCURSOR;
LV_EMP EMP%ROWTYPE;
BEGIN
LV_REF:=EMP_REF_1;
LOOP
FETCH LV_REF INTO LV_EMP;
DBMS_OUTPUT.PUT_LINE(LV_EMP.EMP_NAME);
EXIT WHEN LV_REF%NOTFOUND;
END LOOP;
CLOSE LV_REF;
END;
/
SELECT * FROM EMP_REF()
WHERE ROWNUM<=3;
/

SELECT * FROM EMP;
