---------TABLE FUNCTION

CREATE TYPE T_NUM_LIST IS TABLE OF NUMBER;

SELECT * FROM TABLE(T_NUM_LIST(1,2,3,4,5));

---FUNC. TAHT RETURN COLLECTION 
---TABLE()


--PIPELINED FUNCTION-NOT NECESS.FULLY POPULATED.

---TABLE FUNCTION LOADS ALL THE VALUES INTO COLLECTION AND COLLE. RETURNED TO CALLER
--PIPELINED FUNC.--WHEN THE VALUE IS READY AND SENDBACK TO CALLER

CREATE FUNCITON E_NAME 
RETURN T_EMP_LIST PIPELINED 
AS
LV_EMP_lIST T_EMP_LIST;
BEGIN
FOR I IN (SELECT ENAME FROM EMP)
LOOP
LV_EMP_lIST.EXTEND;
LV_EMP_lIST(LV_EMP_lIST.LAST):=I.ENAME;
RETURN LV_EMP_lIST;
END LOOP;
----------

FOR I IN (SELECT ENAME FROM EMP)
LOOP
PIPE ROW (I.ENAME);
END LOOP;
RETURN;

END;
/

CREATE TYPE EMP_ROW AS
OBJECT (EMPNO NUMBER,ENAME VARCHAR(100),SAL NUMBER)
/

CREATE TYPE T_EMP_LIST IS TABLE OF EMP_ROW;
/
