----CONSTRAINTS
 --CONSTRAINT VALIDATE THE DATA BEFORE GETTING LOADED INTO TABLE
 

ALTER TABLE   EMP ADD CONSTANT EMPNO_PK PRIMARY KEY (EMPNO) DEFERRABLE NOVALIDATE;

---CREATING PK CONSTANT AUTOMATICALLY CREATES THE UNIQUE INDEX PROVIDED IF THERE IS NO INDEX ON THAT COLUMN ALREADY
--

ALTER TABLE TAB_NAME DROP CONSTRAINT EMPNO_PK;
--DROPPING A TBABLE--ALSO DROPS THE INDEX,CONSTRAINTS AND TRIGGER
--DEFERRABLE NOVALIDATE PRIMARY KEY ALSO CREATES A NON UNIQUE INDEX 



CREATE TABLE T
(C NUMBER NOT NULL,
CONSTRAINT UK UNIQUE(C),
CONSTANT PK PRIMARY (C)
)
/


ALTER TABLE SALARY_HISTORY ADD CONSTRAINT SAL_FK FOREIGN KEY (EMP_ID) REFERENCES EMP(E_ID) ON DELETE CASCADE/SET NULL;

ALTER TABLE DEPT DROP COLUMN DEP_ID CASCADE CONSTRAINT;

RENAME/


CREATE TABLE CONT_TB
(CONT_ID NUMBER PRIMARY KEY,
CONT VARCHAR(20));

ALTER TABLE CONT_TB RENAME CONSTRAINT SYS_C0030229 TO CONT_ID_PK;

CREATE TABLE COUNTRY_TB
(C_ID NUMBER,
CONT_ID NUMBER,
CONSTRAINT COUNTRY_FK FOREIGN KEY (CONT_ID) REFERENCES CONT_TB(CONT_ID)
);



SELECT * FROM USER_CONSTRAINTS;

ALTER TABLE CONT_TB ADD  CONT_ID NUMBER PRIMARY KEY;

INSERT INTO CONT_TB VALUES ('ASIA',1);
INSERT INTO CONT_TB VALUES ('EUROPE',2);

ALTER TABLE COUNTRY_TB ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (CONT_ID) DEFERRABLE NOVALIDATE;

ALTER TABLE COUNTRY_TB DROP CONSTRAINT COUNTRY_FK;

INSERT INTO COUNTRY_TB VALUES (20,2);

SELECT * FROM COUNTRY_TB;
