----------MUTATING TRIGGER
CREATE PACKAGE PKG1 AS
LV_MAX_SAL NUMBER;
END PKG1;
/
CREATE OR REPLACE TRIGGER TR_STMT_SAL
BEFORE UPDATE OF SALARY ON EMP
DECLARE
BEGIN

SELECT MAX(SALARY) INTO PKG1.LV_MAX_SAL
FROM EMP;
END;
/

CREATE OR REPLACE TRIGGER TR_SAL
BEFORE UPDATE OF SALARY ON EMP
FOR EACH ROW
DECLARE
BEGIN


IF :NEW.SALARY>PKG1.LV_MAX_SAL
THEN
RAISE_APPLICATION_ERROR (-20001,'TRIGGER FIRED- UPDATING VALUE EXCEEDING LIMIT');
ELSE 
DBMS_OUTPUT.PUT_LINE ('UPDATED SUCCESSFULY OLD VALUE = '||:OLD.SALARY||' NEW VALUE = '||:NEW.SALARY);
END IF ;
END;
/

SET SERVEROUTPUT ON;
UPDATE EMP
SET SALARY=1000000 WHERE EMP_ID=4;
