
---------TYPES OF BINDING
INBIND- TRANSFERRING COLLECTION DATA INTO A TABLE USING FORALL

DECLARE
TYPE T_NUM_LIST_TYPE IS TABLE OF NUMBER;
LV_NUM_LIST T_NUM_LIST_TYPE:=T_NUM_LIST_TYPE(1,2,3,4,5);
BEGIN
FORALL I IN LV_NUM_LIST.FIRST..LV_NUM_LIST.LAST
INSERT INTO A VALUES (LV_NUM_LIST(I));
END;
/

--OUTBIND--RESULT OF AN DML STMT INTO A COLLECTION WITH A MINIMAL CONTEXT SWITCHING 
--USING RETURNING

DECLARE
TYPE T_NUM_LIST_TYPE IS TABLE OF NUMBER;
LV_NUM_LIST T_NUM_LIST_TYPE;
BEGIN
UPDATE A SET COL=COL+100
RETURNING COL
BULK COLLECT INTO LV_NUM_LIST;
END;


---DEFINE
--HOLD OP OF A SELECT STMT INTO PLSQL COLLECTION USING BULK COLLECT
---

------------
--BULK COLLECT CLAUSE CAN USE IN 
--SELECT,FETCH,
--RETURNINIG INTO 
